### ISSUE TITLE
aoe-87pre3-bi_error branch does not compile on kernel 4.8.0

### ISSUE THREAD

**Issue by kalleyne** [OpenAoE/aoe#10]
Starting new issue.
Tried to compile aoe-87pre3-bi_error on kernel 4.8.0 running on Ubuntu 16.04.2 Server LTS HWE. I'm aware that 4.8 is now EOL but Ubuntu 16.04.2 was only just released last week....so our thinking is that folks are still using it (4.8)...at least for a while. Thanks.

Errors during make:

user1@ubuntu-svr-hwe:~/IMG/Coraid/aoe/aoe-87pre3-bi_error$ uname -a
Linux ubuntu-svr-hwe 4.8.0-39-generic #42~16.04.1-Ubuntu SMP Mon Feb 20 15:06:07 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
user1@ubuntu-svr-hwe:~/IMG/Coraid/aoe/aoe-87pre3-bi_error$ make
cd aoetools-36 && make 
make[1]: Entering directory '/home/user1/IMG/Coraid/aoe/aoe-87pre3-bi_error/aoetools-36'
+ sed -e s!@devdir@!/dev/etherd!g -e s!@npershelf@!16!g aoe-discover.in
+ sed -e s!@devdir@!/dev/etherd!g -e s!@npershelf@!16!g aoe-interfaces.in
+ sed -e s!@devdir@!/dev/etherd!g -e s!@npershelf@!16!g aoe-mkshelf.in
+ sed -e s!@devdir@!/dev/etherd!g -e s!@npershelf@!16!g aoe-revalidate.in
+ sed -e s!@devdir@!/dev/etherd!g -e s!@npershelf@!16!g aoe-flush.in
+ sed -e s!@devdir@!/dev/etherd!g -e s!@npershelf@!16!g aoe-stat.in
cc -Wall -O -g -o aoeping.o -c aoeping.c
aoeping.c: In function ‘smart’:
aoeping.c:331:6: warning: variable ‘n’ set but not used [-Wunused-but-set-variable]
  int n;
      ^
cc -Wall -O -g -o linux.o -c linux.c
cc -Wall -O -g -o aoeping aoeping.o linux.o
cc -Wall -O -g -o aoecfg.o -c aoecfg.c
cc -Wall -O -g -o aoecfg aoecfg.o linux.o
cc -Wall -O -g -o aoe-sancheck.o -c aoe-sancheck.c
aoe-sancheck.c: In function ‘jinput’:
aoe-sancheck.c:277:7: warning: variable ‘aa’ set but not used [-Wunused-but-set-variable]
  Ata *aa;
       ^
aoe-sancheck.c: In function ‘sancheck’:
aoe-sancheck.c:614:11: warning: variable ‘mtuflag’ set but not used [-Wunused-but-set-variable]
  int mtu, mtuflag;
           ^
cc -Wall -O -g -o aoe-sancheck aoe-sancheck.o -lpthread
make[1]: Leaving directory '/home/user1/IMG/Coraid/aoe/aoe-87pre3-bi_error/aoetools-36'
sh -c "cd linux/drivers/block/aoe && rm -f *.o *.ko core"
ensuring compatibility ... 1 
patching file linux/drivers/block/aoe/disk_attr.h
2 3 4 5 6 
patching file linux/drivers/block/aoe/aoecmd.c
Hunk #1 succeeded at 978 with fuzz 1 (offset 222 lines).
7 8 9 
patching file linux/drivers/block/aoe/aoeblk.c
Hunk #1 FAILED at 23.
1 out of 1 hunk FAILED -- saving rejects to file linux/drivers/block/aoe/aoeblk.c.rej
patching file linux/drivers/block/aoe/aoecmd.c
Hunk #1 FAILED at 672.
1 out of 1 hunk FAILED -- saving rejects to file linux/drivers/block/aoe/aoecmd.c.rej
Makefile:74: recipe for target 'conf/done' failed
make: *** [conf/done] Error 1

**Comment by ecashin** [comment]
Thanks for the report.  If you're comfortable doing it, you could attach the output of "make report" after repeating this build attempt with newly extracted sources.

**Comment by kalleyne** [comment]
Just for clarity, are we talking about newly extracted sources for aoe-87pre3-bi_error (now v87 - post merge), kernel sources or other? Thanks.

**Comment by kalleyne** [comment]
Let me know if this helps. Thanks.
[aoe6-87pre3-report.tar.gz](https://github.com/OpenAoE/aoe/files/797285/aoe6-87pre3-report.tar.gz)

**Comment by ecashin** [comment]
As we discussed offline, the distro kernels have an aoe driver that has all the features of this standalone version.  I have created a `mothball` branch to make the distro aoe driver the recommended approach for most users, especially those with kernel 4.8.x and higher.
