### ISSUE TITLE
UEFI secure boot: Modprobe, ERROR: could not insert 'aoe': Required key not available

### ISSUE THREAD

**Issue by kalleyne** [OpenAoE/aoe#11]
As discussed in a now closed thread/issue, the unsigned AoE driver may be causing problems for us within UEFI secure boot systems.

While this is not an immediate concern it could definitely be a growing future one. Today, most UEFI systems can still disable secure boot and/or can be switched to Compatibility Support Module (CSM). However, the possibility exists that future systems won't be so accommodating as manufacturers continue to use UEFI secure boot by default and try to hide, conceal and obfuscate sensible alternate boot (BIOS compatibility) methods. It would be at that point that successfully compiling and using AoE may become difficult.

If it is possible, can we determine the size and scope of the effort to sign AoE drivers for usage with UEFI systems?

Thanks so very much.

**Comment by ecashin** [comment]
The distros are solving this problem for the aoe drivers in their kernel packages, so I think the mothball branch is the way to go.  It recommends the distro-provided aoe driver to usual-case users.
