### ISSUE TITLE
end_request: I/O error

### ISSUE THREAD

**Issue by lidaof** [OpenAoE/aoe#2]
Hi,

I am not sure if this issue related to the aoe driver code or not. I was trying to relocating my storage from 1 server to another, the old one has aoe driver version 81 installed, the new has 85 installed, I see this error message on the new system only. Is there a way to fix them? Thanks a lot.

<pre>
Jun 15 17:11:01 cluster kernel: [ 1243.965424] end_request: I/O error, dev etherd/e50.23, sector 1953523728
Jun 15 17:11:01 cluster kernel: [ 1243.965436] aoe: device 52.23 is not up
Jun 15 17:11:01 cluster kernel: [ 1243.965440] end_request: I/O error, dev etherd/e52.23, sector 1953524240
Jun 15 17:11:01 cluster kernel: [ 1243.965443] aoe: device 52.23 is not up
Jun 15 17:11:01 cluster kernel: [ 1243.965445] end_request: I/O error, dev etherd/e52.23, sector 528
Jun 15 17:11:01 cluster kernel: [ 1243.965447] aoe: device 52.23 is not up
Jun 15 17:11:01 cluster kernel: [ 1243.965449] aoe: device 52.23 is not up
Jun 15 17:11:01 cluster kernel: [ 1244.126390] aoe: device 50.23 is not up
Jun 15 17:11:01 cluster kernel: [ 1244.126395] end_request: I/O error, dev etherd/e50.23, sector 1953524240
Jun 15 17:11:01 cluster kernel: [ 1244.177397] aoe: device 50.23 is not up
Jun 15 17:11:01 cluster kernel: [ 1244.177401] end_request: I/O error, dev etherd/e50.23, sector 528
Jun 15 17:11:01 cluster kernel: [ 1244.226678] aoe: device 50.23 is not up
Jun 15 17:11:01 cluster kernel: [ 1244.226681] aoe: device 50.23 is not up
Jun 15 17:11:01 cluster kernel: [ 1244.226697] end_request: I/O error, dev etherd/e52.22, sector 1953523728
Jun 15 17:11:01 cluster kernel: [ 1244.274831] aoe: device 52.22 is not up
Jun 15 17:11:01 cluster kernel: [ 1244.274834] end_request: I/O error, dev etherd/e52.22, sector 1953524240
Jun 15 17:11:01 cluster kernel: [ 1244.321528] aoe: device 52.22 is not up
Jun 15 17:11:01 cluster kernel: [ 1244.321531] end_request: I/O error, dev etherd/e52.22, sector 528
Jun 15 17:11:01 cluster kernel: [ 1244.366733] aoe: device 52.22 is not up
Jun 15 17:11:01 cluster kernel: [ 1244.366736] aoe: device 52.22 is not up
Jun 15 17:11:01 cluster kernel: [ 1244.366760] end_request: I/O error, dev etherd/e50.22, sector 1953523728
Jun 15 17:11:01 cluster kernel: [ 1244.410629] aoe: device 50.22 is not up
Jun 15 17:11:01 cluster kernel: [ 1244.410633] end_request: I/O error, dev etherd/e50.22, sector 1953524240
Jun 15 17:11:01 cluster kernel: [ 1244.453077] aoe: device 50.22 is not up
Jun 15 17:11:01 cluster kernel: [ 1244.453082] aoe: device 50.22 is not up
Jun 15 17:11:01 cluster kernel: [ 1244.453084] aoe: device 50.22 is not up
Jun 15 17:11:01 cluster kernel: [ 1244.453100] aoe: device 52.21 is not up
Jun 15 17:11:01 cluster kernel: [ 1244.453104] aoe: device 52.21 is not up
Jun 15 17:11:01 cluster kernel: [ 1244.453107] aoe: device 52.21 is not up
Jun 15 17:11:01 cluster kernel: [ 1244.453109] aoe: device 52.21 is not up
Jun 15 17:11:01 cluster kernel: [ 1244.453116] aoe: device 50.21 is not up
Jun 15 17:11:01 cluster kernel: [ 1244.453121] aoe: device 50.21 is not up
Jun 15 17:11:01 cluster kernel: [ 1244.453125] aoe: device 50.21 is not up
Jun 15 17:11:01 cluster kernel: [ 1244.453127] aoe: device 50.21 is not up
Jun 15 17:11:01 cluster kernel: [ 1244.453133] aoe: device 52.20 is not up
Jun 15 17:11:01 cluster kernel: [ 1244.453145] aoe: device 52.20 is not up
Jun 15 17:11:01 cluster kernel: [ 1244.453156] aoe: device 52.20 is not up
Jun 15 17:11:01 cluster kernel: [ 1244.453163] aoe: device 52.20 is not up
Jun 15 17:11:01 cluster kernel: [ 1244.453190] aoe: device 50.20 is not up
Jun 15 17:11:01 cluster kernel: [ 1244.453200] aoe: device 50.20 is not up
Jun 15 17:11:01 cluster kernel: [ 1244.453219] aoe: device 50.20 is not up
Jun 15 17:11:01 cluster kernel: [ 1244.453222] aoe: device 50.20 is not up
Jun 15 17:11:01 cluster kernel: [ 1244.453230] aoe: device 52.19 is not up
Jun 15 17:11:01 cluster kernel: [ 1244.453235] aoe: device 52.19 is not up
Jun 15 17:11:01 cluster kernel: [ 1244.453239] aoe: device 52.19 is not up
Jun 15 17:11:01 cluster kernel: [ 1244.453241] aoe: device 52.19 is not up
Jun 15 17:11:01 cluster kernel: [ 1244.453249] aoe: device 52.18 is not up
Jun 15 17:11:01 cluster kernel: [ 1244.453260] aoe: device 52.18 is not up
</pre>

**Comment by ecashin** [comment]
The initiator can't reach the storage at the requested block address. There are many possible reasons. 
E.g., the network connectivity could be interrupted, jumbo frames might not be enabled, the initiator's network interface could be down. 

You might ask the aoetools-discuss mailing list at sourceforge for help in debugging your setup.

**Comment by lidaof** [comment]
Thank you so much for your reply @ecashin .

While my aoe-stat command actually told the system could found the disks:

<pre>
# aoe-stat 
     e50.0      1000.204GB        em1 8704  up            
    e50.10      1000.204GB        em1 8704  up            
     e50.1      1000.204GB        em1 8704  up            
    e50.11      1000.204GB        em1 8704  up            
    e50.12      1000.204GB        em1 8704  up            
    e50.13      1000.204GB        em1 8704  up            
    e50.14      1000.204GB        em1 8704  up            
    e50.15      1000.204GB        em1 8704  up            
    e50.16      1000.204GB        em1 8704  up            
    e50.17      1000.204GB        em1 8704  up            
    e50.18      1000.204GB        em1 8704  up            
    e50.19      1000.204GB        em1 8704  up            
    e50.20      1000.204GB        em1 8704  up            
     e50.2      1000.204GB        em1 8704  up            
    e50.21      1000.204GB        em1 8704  up            
    e50.22      1000.204GB        em1 8704  up            
    e50.23      1000.204GB        em1 8704  up            
     e50.3      1000.204GB        em1 8704  up            
     e50.4      1000.204GB        em1 8704  up            
     e50.5      1000.204GB        em1 8704  up            
     e50.6      1000.204GB        em1 8704  up            
     e50.7      1000.204GB        em1 8704  up            
     e50.8      1000.204GB        em1 8704  up            
     e50.9      1000.204GB        em1 8704  up            
     e52.0      1000.204GB        em1 8704  up            
    e52.10      1000.204GB        em1 8704  up            
     e52.1      1000.204GB        em1 8704  up            
    e52.11      1000.204GB        em1 8704  up            
    e52.12      1000.204GB        em1 8704  up            
    e52.13      1000.204GB        em1 8704  up            
    e52.14      1000.204GB        em1 8704  up            
    e52.15      1000.204GB        em1 8704  up            
    e52.16      1000.204GB        em1 8704  up            
    e52.17      1000.204GB        em1 8704  up            
    e52.18      1000.204GB        em1 8704  up            
    e52.19      1000.204GB        em1 8704  up            
    e52.20      1000.204GB        em1 8704  up            
     e52.2      1000.204GB        em1 8704  up            
    e52.21      1000.204GB        em1 8704  up            
    e52.22      1000.204GB        em1 8704  up            
    e52.23      1000.204GB        em1 8704  up            
     e52.3      1000.204GB        em1 8704  up            
     e52.4      1000.204GB        em1 8704  up            
     e52.5      1000.204GB        em1 8704  up            
     e52.6      1000.204GB        em1 8704  up            
     e52.7      1000.204GB        em1 8704  up            
     e52.8      1000.204GB        em1 8704  up            
     e52.9      1000.204GB        em1 8704  up  
</pre>

I'll try ask the aoe-mailing list, thanks again!
