### ISSUE TITLE
aoe6-86 not compiling on Centos 6.7

### ISSUE THREAD

**Issue by jalbstmeijer** [OpenAoE/aoe#3]
Hi,

I can compile aoe6-85, but aoe6-86 returns:

  CC [M]  BUILD/aoe-aoe6-86/linux/drivers/block/aoe/aoeblk.o
In file included from BUILD/aoe-aoe6-86/linux/drivers/block/aoe/aoeblk.c:17:
BUILD/aoe-aoe6-86/linux/drivers/block/aoe/aoe.h:105: error: field 'iter' has incomplete type
BUILD/aoe-aoe6-86/linux/drivers/block/aoe/aoe.h:124: error: field 'iter' has incomplete type
BUILD/aoe-aoe6-86/linux/drivers/block/aoe/aoeblk.c: In function 'aoe_bio_pagedec':
BUILD/aoe-aoe6-86/linux/drivers/block/aoe/aoeblk.c:35: error: storage size of 'iter' isn't known
BUILD/aoe-aoe6-86/linux/drivers/block/aoe/aoeblk.c:37: error: incompatible types when assigning to type 'struct bio_vec' from type 'struct bio_vec _'
BUILD/aoe-aoe6-86/linux/drivers/block/aoe/aoeblk.c:37: warning: left-hand operand of comma expression has no effect
BUILD/aoe-aoe6-86/linux/drivers/block/aoe/aoeblk.c:37: error: wrong type argument to increment
BUILD/aoe-aoe6-86/linux/drivers/block/aoe/aoeblk.c:37: warning: left-hand operand of comma expression has no effect
BUILD/aoe-aoe6-86/linux/drivers/block/aoe/aoeblk.c:35: warning: unused variable 'iter'
make[2]: *_\* [BUILD/aoe-aoe6-86/linux/drivers/block/aoe/aoeblk.o] Error 1
make[1]: **\* [_module_BUILD/aoe-aoe6-86/linux/drivers/block/aoe] Error 2

Gr, J

**Comment by ecashin** [comment]
Thanks for the information. Can you please provide the tarball that results from "make report"?

**Comment by jalbstmeijer** [comment]
tar.gz can not be attached.

Unfortunately, we don’t support that file type. Try again with a PNG, GIF, JPG, DOCX, PPTX, XLSX, TXT, PDF, or ZIP. 

Made a zip of it.
[aoe6-86-report.zip](https://github.com/OpenAoE/aoe/files/61176/aoe6-86-report.zip)

**Comment by ecashin** [comment]
Thanks. I'll try to look into this tonight.

**Comment by ecashin** [comment]
Hi.  Can you please try v87pre1, released tonight with a fix for the compatibility test associated with immutable biovec support?

On my CentOS 6.7 system, v87pre1 builds successfully but v86 does not.

**Comment by jalbstmeijer** [comment]
It compiles now, thank you!

Is this the only change compared to v86? is it save to use?

**Comment by ecashin** [comment]
Yes, it's just a backwards compatibility patch that your older kernel needs to remove the changes that were required for new kernels.
